### PR TITLE
Improve content

### PR DESCRIPTION
**Pull request by CG-bitto**

### CODE REVIEW

**Comment by CG-bitto** [comment]
Hey Nick I am just want to take free t shirt from hactober fest that all
plz accept it.

**Comment by partofthething** [comment]
Gotcha. Sorry that change you proposed actually breaks the build of the website so I can't!

**Comment by CG-bitto** [comment]
So send me some changes

**Comment by CG-bitto** [comment]
And why my pull request was not disable from hactober fest

**Pull request closed without merging**
