### PR TITLE
Create hyatt-regency

### PR DESCRIPTION
**Pull request by riddlemp**
HR_Collapse
First attempt to add directly to the safetyminutes repository, apologize for trouble I'm causing if any (using this as a learning opportunity). I have referenced in code to the image file I have for this safety minute but no push access to img. Image attached to pull request

### CODE REVIEW

**Comment by partofthething** [comment]
This is great, thanks for adding! It rendered ok the first time! A few things I'm doing on a commit that I'll try to send back to you:

* The file has to have extension `.md` so that the system knows it's a Markdown file 
* I added `riddle` to our authors list with display name `Michael Riddle` so it will show that at the top
* I word wrapped the lines differently (doesn't really matter)
* I changed a few <b> bolds to markdown-style `**` things (also doesn't really matter)

As for the image, I can help integrate that as well. One question though: do you have a source for the image we can include (and ensure we have rights to re-host it?). Alternatively, we can readily use any of these: https://commons.wikimedia.org/wiki/Category:Hyatt_Regency_walkway_collapse

**Comment by partofthething** [comment]
If you want to try this feature out by finding and pressing this checkbox on your pull request branch I can commit these tweaks directly to this: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

**Comment by riddlemp** [comment]
Picture was sourced from Springfield News-Leader, photo copyright Bob Linder. We can use another photo, literally just the first one I pulled from my file.

**Comment by partofthething** [comment]
K I think texas A&M photos are public domain so I just chose one of those. I have it all ready to rock over on this branch https://github.com/whatisnuclear/website/compare/master...hyatt

We can talk for a sec in the morning about whether we want to update your branch or just merge in that one. Other than that I think it's GTG. THANKS AGAIN.

**Review by partofthething — APPROVED** [review]
aha there we go. Finally got my commits added. Ok thanks man this is great!

**Pull request merged**
